# CS 136: Intro to Numerical Python

A Python-based version of the "Ch 2 lab" from James et al.'s "Introduction to Statistical Learning" textbook

Based on original notebook: https://nbviewer.jupyter.org/github/emredjan/ISL-python/blob/master/labs/lab_02.3_introduction.ipynb

# What to Do

Students should run this notebook on their own, interactively modifying cells as needed to understand concepts and have hands-on practice.

Try to make sure you can *predict* what a function will do. Build a mental model of NumPy array operations that will make you a better programmer and ML engineer.

Ask questions like:

* what should the result's output type be?
* what should the result's *shape* be?
* what should the result's *values* be?

# Outline

* [Data types](#data_types)
* [Dimension and shape](#dimension_and_shape)
* [Indexing](#indexing)
* [Reshaping and newaxis](#reshaping)
* [Elementwise multiplication](#elementwise_multiplication)
* [Matrix multiplication](#matrix_multiplication)
* [Reductions](#reductions)
-- min
-- max
-- sum
-- prod
* [Random numbers and random permutations](#prng)
* [Useful functions](#useful_functions)
-- linspace, logspace, arange
-- sort, argsort
-- allclose


# Key Takeaways

* Numpy array types (`np.ndarray`) have a DIMENSION, a SHAPE, and a DATA-TYPE (dtype)

* * Every time you write code, make sure you know all 3 for every array

* Consider using standard notation to avoid confusion

* * 1-dim arrays of size N could be named `a_N` or `b_N` instead of `a` or `b`

* * 2-dim arrays of size (M,N) could be named `a_MN` instead of `a`

* * With this notation, it is far more clear that `np.matmul(a_MN, b_N)` will work, but `np.matmul(a_MN.T, b_N)` will not

* Broadcasting is a key concept to understand

* * See https://numpy.org/doc/stable/user/basics.broadcasting.html

* Always use np.array. Avoid np.matrix 

* * Why? Array is more flexible (can be 1-dim, 2-dim, 3-dim, 4-dim, and more!)

# Further Reading

* Stefan van der Walt, S. Chris Colbert, Gaël Varoquaux. The NumPy array: a structure for efficient numerical computation. Computing in Science and Engineering, Institute of Electrical and Electronics Engineers, 2011. 
<https://hal.inria.fr/inria-00564007/document>

* https://realpython.com/numpy-array-programming/


In [ ]:
# import numpy (array library)
import numpy as np


# Basic array creation and manipulation

We use `np.array(...)` function to create arrays

In [ ]:
x = np.array([1.0, 6.0, 2.4]);
print(x);

[1.  6.  2.4]


Numpy stores arrays as type `ndarray` for n-dimensional array.

This type flexibly allows any shape (1-d array, 2-d array, etc.)

In [ ]:
type(x)

numpy.ndarray

In [ ]:
x + 2 # element-wise addition

array([3. , 8. , 4.4])

In [ ]:
x * 2 # element-wise multiplication

array([ 2. , 12. ,  4.8])

In [ ]:
x / 2 # element-wise division

array([0.5, 3. , 1.2])

In [ ]:
x + x # operators like '+' can add two arrays of SAME size

array([ 2. , 12. ,  4.8])

In [ ]:
x / x # so can operators like '/', for element-wise division

array([1., 1., 1.])

<a id="data_types"></a>

# Data types

Arrays have *data types* (or "dtypes")

In [ ]:
y = np.array([1., 4, 3]) # with decimal point in "1.", defaults to 'float' type
print(y)
print(y.dtype)

[1. 4. 3.]
float64


In [ ]:
y_int = np.array([1, 4, 3]) # without decimal point, defaults to 'int' type
print(y_int)
print(y_int.dtype)

[1 4 3]
int64


In [ ]:
y_float32 = np.array([123.], dtype=np.float32) # use optional keyword argument ('kwarg') to specify data type
print(y_float32)
print(y_float32.dtype)

[123.]
float32


In [ ]:
y_float64 = np.array([123.], dtype=np.float64)

In [ ]:
print("y_float32:")
print("  num bytes", y_float32.nbytes) # each entry is 32bits = 4 bytes
print("y_float64:")
print("  num bytes", y_float64.nbytes) # each entry is 64bits = 8 bytes

y_float32:
  num bytes 4
y_float64:
  num bytes 8


In [ ]:
# What happens when you add float32 to float64? 
# result is *upcast* so no precision is lost
z = y_float64 + y_float32 
print(z)
print(z.dtype)

[246.]
float64


<a id="dimension_and_shape"></a>

# Dimension and Shape

Arrays have DIMENSION and SHAPE

Dimension = an integer value : number of integers needed to index a unique entry of the array

Shape = a tuple of integers : each entry gives the size of the corresponding dimension


In [ ]:
y

array([1., 4., 3.])

In [ ]:
y.ndim

1

In [ ]:
y.shape

(3,)

In [ ]:
# Create 2D 3x3 array 'M' as floats
M = np.asarray([[1, 4, 7.0], [2, 5, 8], [3, 6, 9]])
print(M)

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [ ]:
print(M.ndim)

2


In [ ]:
print(M.shape)

(3, 3)


In [ ]:
# Create 2D *rectangular* array
M_35 = np.asarray([[1, 4, 7.0, 10, 13], [2, 5, 8, 11, 14], [3, 6, 9, 12, 15]])
print(M_35)

[[ 1.  4.  7. 10. 13.]
 [ 2.  5.  8. 11. 14.]
 [ 3.  6.  9. 12. 15.]]


In [ ]:
M_35.shape

(3, 5)

## CS 135 shape-suffix notation

Convention throughout this semester: 

Every variable whose type is `ndarray` has in its name a suffix that indicates *shape*

* `_3` suffix denotes array whose shape is always (3,)
* `_A` suffix denotes array with shape (A,), where A is a problem-specific variable
* `_AB` suffix to denote an array with shape (A, B)

Please try to use this convention! You'll be surprised how much it helps with clear thinking and debugging

<a id="indexing"></a>

# Indexing numpy arrays

Sometimes, we want to grab just one row or just one column of interest.

In [ ]:
# Let's make an interesting array of size 4x4
# Don't worry about this creation command just yet, focus on what we do with this 4x4 array
A_44 = np.arange(1, 17).reshape(4, 4).transpose() 
A_44

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [ ]:
# Show the first row. Remember Python counts starting at 0
A_44[0]

array([ 1,  5,  9, 13])

In [ ]:
# Show the first col
A_44[:, 0]

array([1, 2, 3, 4])

In [ ]:
# Grab the second row
A_44[1]

array([ 2,  6, 10, 14])

In [ ]:
# Select a range of rows, from index 0 (inclusive) to index 3 (exclusive)
A_44[0:3]

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [ ]:
# Select a range of *rows* and a specific range of columns
A_44[0:3, 1:4]

array([[ 5,  9, 13],
       [ 6, 10, 14],
       [ 7, 11, 15]])

In [ ]:
# select a range of rows and all columns
A_44[0:2,:]

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14]])

In [ ]:
# Grab the *last* row
A_44[-1]

array([ 4,  8, 12, 16])

In [ ]:
# Select the *second to last* column
A_44[:, -2]

array([ 9, 10, 11, 12])

## Indexing with an iterable of integers

Suppose we want the rows that correspond to ids 1 and 3

The following are all equivalent ways to do that

In [ ]:
A_44[ [1,3]]

array([[ 2,  6, 10, 14],
       [ 4,  8, 12, 16]])

In [ ]:
row_ids = [1,3]
A_44[row_ids]  # row_ids has type 'list'

array([[ 2,  6, 10, 14],
       [ 4,  8, 12, 16]])

In [ ]:
row_ids = np.asarray([1,3], dtype=np.int32)
A_44[row_ids]  # row_ids has type 'np.ndarray', with elements that are *int* valued

array([[ 2,  6, 10, 14],
       [ 4,  8, 12, 16]])

We *cannot* do the same thing with an array of floats


In [ ]:
row_ids_f64 = np.asarray(row_ids, dtype=np.float64)
try:
    A_44[row_ids_f64]
except Exception as e:
    print(type(e).__name__)
    print(e)

IndexError
arrays used as indices must be of integer (or boolean) type


The provided list of indices can include multiples and can be unsorted

In [ ]:
more_ids = np.asarray([3, 3, 1, 0], dtype=np.int32)
A_44[more_ids]

array([[ 4,  8, 12, 16],
       [ 4,  8, 12, 16],
       [ 2,  6, 10, 14],
       [ 1,  5,  9, 13]])

<a id="reshaping"></a>

# Reshaping and newaxis

Sometimes, we want to transform from 1-dim to 2-dim arrays, or from 2- to 3-dim arrays.

We can either use:
* the *reshape* function
* indexing with the "np.newaxis" built-in <https://numpy.org/doc/stable/reference/constants.html#numpy.newaxis>


### Demo of reshape

In [ ]:
y = np.array([1.0, 4, 3])
print(y)
print(y.shape)

[1. 4. 3.]
(3,)


In [ ]:
y_13 = np.reshape(y, (1,3))  # use '_AB' suffix to denote an array with shape (A, B)
print(y_13)
print(y_13.shape)

[[1. 4. 3.]]
(1, 3)


In [ ]:
y_31 = np.reshape(y, (3, 1))  # use '_AB' suffix to denote an array with shape (A, B)
print(y_31)
print(y_31.shape)

[[1.]
 [4.]
 [3.]]
(3, 1)


In [ ]:
y_3 = np.array([1.0, 4, 3])
print(y_3)
print(y_3.shape)

[1. 4. 3.]
(3,)


In [ ]:
y_13 = y[np.newaxis,:] # use newaxis to insert new single dimension
print(y_13)

[[1. 4. 3.]]


In [ ]:
print(y_13.shape)

(1, 3)


In [ ]:
y_31 = y[:, np.newaxis]
print(y_31)

[[1.]
 [4.]
 [3.]]


In [ ]:
print(y_31.shape)

(3, 1)


In [ ]:
y_311 = y[:, np.newaxis, np.newaxis]
print(y_311)

[[[1.]]

 [[4.]]

 [[3.]]]


In [ ]:
print(y_311.shape)

(3, 1, 1)


## Demo: how newaxis can help

In [ ]:
x_33 = np.array([[5., 2, 1], [4, 2, 6], [1, 1, 0]])
print(x_33)

[[5. 2. 1.]
 [4. 2. 6.]
 [1. 1. 0.]]


In [ ]:
y_23 = np.array([[1.0, 4, 3], [2, 1, 4]])
print(y_23)

[[1. 4. 3.]
 [2. 1. 4.]]


Suppose you want to subtract each row in y from each row in x 

You could use a for loop, but we'll learn that forloops in python are slow and should be avoided if possible for efficient code.

We might wish to do 

```
x_33 - y_23
```

However, this will not work out of the box... there's a ValueError that will result.


In [ ]:
try:
    x_33 - y_23
except Exception as e:
    print(type(e).__name__)
    print(e)

ValueError
operands could not be broadcast together with shapes (3,3) (2,3) 


Instead, we can accomplish our goal (subtract each row of x from each row of y) by

* making x into a 3d array with a newaxis at dim 1
* making y into a 3d array with a newaxis at dim 0

Then, they have compatible shapes, and the "-" operator can work!

In [ ]:
x_313 = x_33[:,np.newaxis,:]

y_123 = y_23[np.newaxis,:,:]

z_323 = x_313 - y_123

print(z_323)

[[[ 4. -2. -2.]
  [ 3.  1. -3.]]

 [[ 3. -2.  3.]
  [ 2.  1.  2.]]

 [[ 0. -3. -3.]
  [-1.  0. -4.]]]


In [ ]:
# First row of y subtracted from all rows of x
z_323[:,0,:]

array([[ 4., -2., -2.],
       [ 3., -2.,  3.],
       [ 0., -3., -3.]])

In [ ]:
# Second row of y subtracted from all rows of x
z_323[:,1,:]

array([[ 3.,  1., -3.],
       [ 2.,  1.,  2.],
       [-1.,  0., -4.]])

<a id="elementwise_multiplication"></a>

# Elementwise Multiplication

To perform *element-wise* multiplication, use '*' symbol

In [ ]:
print(y)

[1. 4. 3.]


In [ ]:
print(M)

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [ ]:
R = M * M
print(R)

[[ 1. 16. 49.]
 [ 4. 25. 64.]
 [ 9. 36. 81.]]


In [ ]:
# What happens when we multiply (3,3) shape by a (3,) shape?
# y is implicitly expanded to (1,3) and thus multiplied element-wise to each row

In [ ]:
M * y

array([[ 1., 16., 21.],
       [ 2., 20., 24.],
       [ 3., 24., 27.]])

In [ ]:
M * y[np.newaxis,:]  # same thing as above, but more explicit

array([[ 1., 16., 21.],
       [ 2., 20., 24.],
       [ 3., 24., 27.]])

In [ ]:
M * y[:,np.newaxis]  # this makes y multiplied to each column

array([[ 1.,  4.,  7.],
       [ 8., 20., 32.],
       [ 9., 18., 27.]])

In NumPy, multiplying an (M,N) array by an (M,) array is known as *broadcasting*

NumPy's *implicit* rules for what happens are defined here:

https://numpy.org/doc/stable/user/basics.broadcasting.html

CS 135 Code Style: We suggest **explicit** is better than implicit

In [ ]:
# OK, will run, but hard to understand
M * y

array([[ 1., 16., 21.],
       [ 2., 20., 24.],
       [ 3., 24., 27.]])

In [ ]:
# Preferred
M_33 = M
y_13 = y_3[np.newaxis,:]
M_33 * y_13

array([[ 1., 16., 21.],
       [ 2., 20., 24.],
       [ 3., 24., 27.]])

<a id="matrix_multiplication"></a>

# Matrix multiplication, refresher

Recall the basic definition of a **matrix multiplication** from mathematics. See <https://en.wikipedia.org/wiki/Matrix_multiplication>

We are given two input matrices: 

* $A$ of shape $(m,n)$
* $B$ of shape $(n,p)$

The multiplication of $A$ by $B$ produces a new matrix

* $C$ of shape $(m,p)$

The matrix multiply operation $\texttt{MatrixMult}(A,B)$ is often denoted by simple "no operator" notation: $A B$

The formal definition of the result $C = A B$ of this operation is that we build matrix $C$ so that its $i,k$-th entry is

$$
C_{i,k} = \sum_{j=1}^n A_{i,j} B_{j,k}
$$

for valid indices $i \in \{1, 2, \ldots m\}$ and $k \in \{1, 2, \ldots p\}$.

See diagram of matrix multiplication below

<table>
    <tr>
        <td>
        <img width=400px src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Matrix_multiplication_qtl1.svg/1024px-Matrix_multiplication_qtl1.svg.png">
        <td>
        <img width=400px src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Matrix_multiplication_diagram_2.svg/330px-Matrix_multiplication_diagram_2.svg.png">
        </td>
    </tr>
</table>

# Matrix multiplication via np.matmul

In NumPy, we can use `np.matmul` to perform matrix multiplication.

Docs for `np.matmul`: <https://numpy.org/doc/stable/reference/generated/numpy.matmul.html>

Keep in mind, the "type" of all the variables here is still NumPy's ND-array. There is no special "matrix" or "vector" type.

In [ ]:
M_33

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

In [ ]:
y_3 = np.array([1.0, 4, 3])
y_3

array([1., 4., 3.])

## matmul of (3,3) and (3,1) arrays

In [ ]:
np.matmul(M_33, y_3[:,np.newaxis])

array([[38.],
       [46.],
       [54.]])

## matmul of (3,3) array with itself

In [ ]:
np.matmul(M_33, M_33)

array([[ 30.,  66., 102.],
       [ 36.,  81., 126.],
       [ 42.,  96., 150.]])

## matmul of (3,) array with itself = inner product of that 'vector' with itself

In [ ]:
np.matmul(y_3, y_3)

26.0

In [ ]:
np.inner(y_3, y_3)

26.0

In [ ]:
np.sum(np.square(y_3)) #another way to write an inner product

26.0

## Verify: matmul works even if we 'reshape' y to do (1,3) x (3,1) matrix product

In [ ]:
y_13 = y_3[np.newaxis,:]
y_31 = y_3[:,np.newaxis]

np.matmul(y_13, y_31)

array([[26.]])

<a id="pseudorandom_number_generation"></a>

<a id="prng"></a>

# Pseudorandom number generation

### Generate 15 values uniformly distributed between 0 and 1

In [ ]:
x = np.random.uniform(size=15) 
print(x)

[0.43712257 0.88612673 0.76701159 0.99264217 0.47212508 0.87899298
 0.87038322 0.05296748 0.38636216 0.17110279 0.32797272 0.28355739
 0.48347777 0.17383597 0.29097257]


### Generate 15 float values normally distributed according to 'standard' normal (mean 0, variance 1)


In [ ]:
x = np.random.normal(size=15)
print(x)

[ 0.56329    -0.80961345  1.57636708  0.12752517  0.28277707 -0.6204834
  0.30154359 -0.20037812  0.89625099  0.90651468  0.92620566  1.55300323
  0.0969203   0.81211239  0.40441021]


### To make *repeatable* pseudo-randomness, use a generator with the same seed!

A "seed" can just be any *positive* integer. It completely determines how the generator produces its sequence of "random" values

Note: prng is short for pseudo-random number generator, see https://en.wikipedia.org/wiki/Pseudorandom_number_generator

In [ ]:
seedA = 9876
seedB = 1234
prng = np.random.RandomState(seedA) 
prng.uniform(size=10)

array([0.1636023 , 0.62062216, 0.90113139, 0.7664971 , 0.51324219,
       0.0966023 , 0.45981236, 0.13687653, 0.94882576, 0.49120575])

In [ ]:
prng = np.random.RandomState(seedA)
prng.uniform(size=10)               # should be SAME as above

array([0.1636023 , 0.62062216, 0.90113139, 0.7664971 , 0.51324219,
       0.0966023 , 0.45981236, 0.13687653, 0.94882576, 0.49120575])

In [ ]:
prng = np.random.RandomState(seedB)
prng.uniform(size=10)              # should be DIFFERENT than above, because seed is different

array([0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581,
       0.27259261, 0.27646426, 0.80187218, 0.95813935, 0.87593263])

### To "shuffle" or permute a sequence, use the permutation function

In [ ]:
my_array_5 = np.arange(1,6)

In [ ]:
my_array_5

array([1, 2, 3, 4, 5])

In [ ]:
prng = np.random.RandomState(8675309)
prng.permutation(my_array_5) # shuffle the sequence

array([3, 5, 4, 1, 2])

In [ ]:
prng.permutation(my_array_5) # shuffle it again

array([3, 4, 2, 5, 1])

In [ ]:
prng.permutation(my_array_5) # shuffle the sequence again

array([4, 2, 1, 3, 5])

<a id="useful_functions"></a>

# Useful functions

## zeros : Create array of all zeros of desired shape and dtype

* Remember, the default dtype is `np.float64`

In [ ]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.zeros((1,2,3), dtype=np.int32) # provide desired dtype

array([[[0, 0, 0],
        [0, 0, 0]]], dtype=int32)

### ones : Create array of all ones of desired shape and dtype

In [ ]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,9), dtype=np.int32)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)

### linspace : Linearly spaced numbers between provided low and high values


In [ ]:
N = 5
x_N = np.linspace(-2, 2, num=N)
x_N

array([-2., -1.,  0.,  1.,  2.])

### logspace : Logarithmically spaced numbers between provided low and high values

In [ ]:
x_N = np.logspace(-2, 2, base=10, num=N)
x_N

array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02])

### arange : evenly spaced values in given interval

https://numpy.org/doc/stable/reference/generated/numpy.arange.html

Remember, Python counting conventions: 

* start at 0 by default
* the inner bound is *inclusive*
* the upper bound is *exclusive*

In [ ]:
# Start at 0 (default), count up by 1 (default) until you get to 4 (exclusive)
x = np.arange(4)
print(x)

[0 1 2 3]


In [ ]:
# Start at negative PI, count up by increments of pi/4 until you get to + PI (exclusive)

y = np.arange(start=-np.pi, stop=np.pi, step=np.pi/4)
print(y)

[-3.14159265 -2.35619449 -1.57079633 -0.78539816  0.          0.78539816
  1.57079633  2.35619449]


In [ ]:
# Start at negative PI, count up by increments of pi/4 until you get to PI + very small number (exclusive)

y = np.arange(start=-np.pi, stop=np.pi + 0.0000001, step=np.pi/4)
print(y)

[-3.14159265 -2.35619449 -1.57079633 -0.78539816  0.          0.78539816
  1.57079633  2.35619449  3.14159265]


### allclose : verify if all values in an array are "close enough"

https://numpy.org/doc/stable/reference/generated/numpy.allclose.html

Useful when checking if entries in an array are "close enough" to some reference value

E.g. sometimes due to numerical issues of representation, we would consider 5.00002 as good as "5"

In [ ]:
x_N = np.arange(4)
print(x_N)

[0 1 2 3]


In [ ]:
x2_N = x_N + 0.000001
print(x2_N)

[1.000000e-06 1.000001e+00 2.000001e+00 3.000001e+00]


In [ ]:
np.all(x_N == x2_N)

False

In [ ]:
np.allclose(x_N, x2_N, atol=0.01) # 'atol' is *absolute tolerance*

True

In [ ]:
np.allclose(x_N, x2_N, atol=1e-7) # trying with too small a tolerance will result in False

False

### sort : sort values in *ascending* order

In [ ]:
np.sort([3, 4, 5, 1, 2])

array([1, 2, 3, 4, 5])

In [ ]:
A_25= np.asarray([
    [3,4,5,1,2],
    [9,7,8,6,0],
])
A_25

array([[3, 4, 5, 1, 2],
       [9, 7, 8, 6, 0]])

Sorting ND arrays requires specifying an axis

In [ ]:
np.sort(A_25, axis=0) # sort across first dim (sort each column)

array([[3, 4, 5, 1, 0],
       [9, 7, 8, 6, 2]])

In [ ]:
np.sort(A_25, axis=1) # sort across second dim (sort each row)

array([[1, 2, 3, 4, 5],
       [0, 6, 7, 8, 9]])

### argsort : get indices that are usable to sort the array

In [ ]:
arr_3 = np.asarray([5.9, 0, 3., -2.1])

In [ ]:
ids_3 = np.argsort(arr_3)
ids_3

array([3, 1, 2, 0])

In [ ]:
arr_3[ids_3]

array([-2.1,  0. ,  3. ,  5.9])

For ND arrays, you can again provide an `axis` argument

In [ ]:
A_25

array([[3, 4, 5, 1, 2],
       [9, 7, 8, 6, 0]])

In [ ]:
np.argsort(A_25, axis=0)

array([[0, 0, 0, 0, 1],
       [1, 1, 1, 1, 0]])

In [ ]:
np.argsort(A_25, axis=1)

array([[3, 4, 0, 1, 2],
       [4, 3, 1, 2, 0]])

<a id="reductions"></a>

# Reductions


Some numpy functions like '[sum](https://numpy.org/doc/stable/reference/generated/numpy.sum.html
)' or 'prod' or 'max' or 'min' that take in arrays with many values and produce fewer values.

These kinds of operations are known as "reductions": https://numpy.org/doc/stable/reference/generated/numpy.ufunc.reduce.html

Within numpy, any reduction function takes an optional 'axis' keyword argument ("kwarg") to specify specific dimensions to apply the reduction to


In [ ]:
# 2D array creation
A_44 = np.arange(1, 17).reshape(4, 4).transpose()
A_44

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [ ]:
np.sum(A_44) # sum of all entries of A

136

In [ ]:
np.sum(A_44, axis=0) # sum across dim with index 0 (across rows)

array([10, 26, 42, 58])

In [ ]:
np.sum(A_44, axis=1) # sum across dim with index 1 (across cols)

array([28, 32, 36, 40])

In [ ]:
np.min(A_44, axis=1) # compute minimum across dim with index 1

array([1, 2, 3, 4])

<a id="indexing"></a>

In [ ]:
# 3D arrays now
Q_234 = np.arange(1, 25).reshape((2,3,4))
Q_234

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [ ]:
np.min(Q_234, axis=0) # minimum along dim with index 0

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.min(Q_234, axis=1)

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [ ]:
np.min(Q_234, axis=2)

array([[ 1,  5,  9],
       [13, 17, 21]])

In [ ]:
np.min(Q_234, axis=(1,2)) # minimum along two dimensions, at index 1 and 2

array([ 1, 13])